### ISSUE TITLE
Dynamically create context in before 

### ISSUE THREAD

**Issue by riaan53** [iwhitfield/it.each#2]
Hi,

Thank you for this great lib!

One question. I need to async get all the connected devices (over websockets) and then perform the tests on all of them. How can I do that with this lib if possible? In example below self.devices is empty in the it.each call but the context is correct in the callback function console.log.

```js
describe('Array', function() {
  describe('#indexOf()', function(){
    this.devices = [];
    var self = this;

    before(function(done) {
      getAllConnectedDevices(function(devices) {
        self.devices = devices;
        done();
      });
    })

    it.each(self.devices, 'should return -1 when the value is not present when searching for {os}', function(elem, done){
      console.log(self.devices);
      assert.equal(-1, [1,2,3].indexOf(2));
      done();
    })
  })
})
```

Thanks!

Regards,
Riaan

**Comment by iwhitfield** [comment]
Ah, this is a mocha use-case rather than this library. Mocha is not running all statements as it hits, rather it queues them up before execution. This means that your `before` is not executed before queuing `it.each` (i.e. before self.devices is defined). 

One way around this would be something like:

```
getAllConnectedDevices(function(devices) {
    self.devices = devices;
        
    it.each(self.devices, 'should return -1 when the value is not present when searching for {os}', function(elem, done){
        console.log(self.devices);
        assert.equal(-1, [1,2,3].indexOf(2));
        done();
    });

});
```

**Comment by iwhitfield** [comment]
I'm gonna close this because I'm pretty certain it's just the nature of Mocha, rather than the extension (you'd have the same problem if you did it with just an `it`).

If you find anything showing it is this lib, feel free to reopen it!
